
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: PythonPackage
  displayName: 'Python Package Stage'
  jobs:
  - job: PythonJob
    displayName: 'Python Job'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.11.2'

    - checkout: self  
      persistCredentials: true  

    - task: PythonScript@0
      displayName: 'Execute Python script'
      inputs:
        scriptSource: 'filePath'
        scriptPath: 'hello.py'  # Update this with the actual path to your Python script within the repository

- stage: MavenBuild
  displayName: 'Maven Build Stage'
  jobs:
  - job: MavenJob
    displayName: 'Maven Job'
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'  # Path to your Maven POM file
        goals: 'clean package'  # Maven goals to execute
        options: '-Xmx3072m'  # Optional Maven command-line options
        publishJUnitResults: true  # Publish JUnit test results if available

