# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11.2'



- checkout: self  # This step checks out your repository
  persistCredentials: true  # If your repository requires credentials, this ensures they're persisted for subsequent steps

- task: PythonScript@0
  displayName: 'Execute Python script'
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'Python-Programs/jugsmugspugs.py'  # Update this with the actual path to your Python script within the repository

